// Code generated by entc, DO NOT EDIT.

package nearbyplace

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team15/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Nearbyplace applies equality check predicate on the "nearbyplace" field. It's identical to NearbyplaceEQ.
func Nearbyplace(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceEQ applies the EQ predicate on the "nearbyplace" field.
func NearbyplaceEQ(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceNEQ applies the NEQ predicate on the "nearbyplace" field.
func NearbyplaceNEQ(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceIn applies the In predicate on the "nearbyplace" field.
func NearbyplaceIn(vs ...string) predicate.Nearbyplace {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nearbyplace(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNearbyplace), v...))
	})
}

// NearbyplaceNotIn applies the NotIn predicate on the "nearbyplace" field.
func NearbyplaceNotIn(vs ...string) predicate.Nearbyplace {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nearbyplace(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNearbyplace), v...))
	})
}

// NearbyplaceGT applies the GT predicate on the "nearbyplace" field.
func NearbyplaceGT(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceGTE applies the GTE predicate on the "nearbyplace" field.
func NearbyplaceGTE(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceLT applies the LT predicate on the "nearbyplace" field.
func NearbyplaceLT(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceLTE applies the LTE predicate on the "nearbyplace" field.
func NearbyplaceLTE(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceContains applies the Contains predicate on the "nearbyplace" field.
func NearbyplaceContains(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceHasPrefix applies the HasPrefix predicate on the "nearbyplace" field.
func NearbyplaceHasPrefix(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceHasSuffix applies the HasSuffix predicate on the "nearbyplace" field.
func NearbyplaceHasSuffix(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceEqualFold applies the EqualFold predicate on the "nearbyplace" field.
func NearbyplaceEqualFold(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNearbyplace), v))
	})
}

// NearbyplaceContainsFold applies the ContainsFold predicate on the "nearbyplace" field.
func NearbyplaceContainsFold(v string) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNearbyplace), v))
	})
}

// HasRoomdetail applies the HasEdge predicate on the "roomdetail" edge.
func HasRoomdetail() predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomdetailTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomdetailTable, RoomdetailColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoomdetailWith applies the HasEdge predicate on the "roomdetail" edge with a given conditions (other predicates).
func HasRoomdetailWith(preds ...predicate.Roomdetail) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(RoomdetailInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoomdetailTable, RoomdetailColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Nearbyplace) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Nearbyplace) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Nearbyplace) predicate.Nearbyplace {
	return predicate.Nearbyplace(func(s *sql.Selector) {
		p(s.Not())
	})
}
