// Code generated by entc, DO NOT EDIT.

package equipment

const (
	// Label holds the string label denoting the equipment type in the database.
	Label = "equipment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEquipment holds the string denoting the equipment field in the database.
	FieldEquipment = "equipment"

	// EdgeRoom holds the string denoting the room edge name in mutations.
	EdgeRoom = "room"

	// Table holds the table name of the equipment in the database.
	Table = "equipment"
	// RoomTable is the table the holds the room relation/edge. The primary key declared below.
	RoomTable = "room_equipments"
	// RoomInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	RoomInverseTable = "rooms"
)

// Columns holds all SQL columns for equipment fields.
var Columns = []string{
	FieldID,
	FieldEquipment,
}

var (
	// RoomPrimaryKey and RoomColumn2 are the table columns denoting the
	// primary key for the room relation (M2M).
	RoomPrimaryKey = []string{"room_id", "equipment_id"}
)
