// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/cleanername"
	"github.com/team15/app/ent/predicate"
)

// CleanerNameDelete is the builder for deleting a CleanerName entity.
type CleanerNameDelete struct {
	config
	hooks      []Hook
	mutation   *CleanerNameMutation
	predicates []predicate.CleanerName
}

// Where adds a new predicate to the delete builder.
func (cnd *CleanerNameDelete) Where(ps ...predicate.CleanerName) *CleanerNameDelete {
	cnd.predicates = append(cnd.predicates, ps...)
	return cnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cnd *CleanerNameDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cnd.hooks) == 0 {
		affected, err = cnd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CleanerNameMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cnd.mutation = mutation
			affected, err = cnd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cnd.hooks) - 1; i >= 0; i-- {
			mut = cnd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cnd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cnd *CleanerNameDelete) ExecX(ctx context.Context) int {
	n, err := cnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cnd *CleanerNameDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: cleanername.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cleanername.FieldID,
			},
		},
	}
	if ps := cnd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cnd.driver, _spec)
}

// CleanerNameDeleteOne is the builder for deleting a single CleanerName entity.
type CleanerNameDeleteOne struct {
	cnd *CleanerNameDelete
}

// Exec executes the deletion query.
func (cndo *CleanerNameDeleteOne) Exec(ctx context.Context) error {
	n, err := cndo.cnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cleanername.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cndo *CleanerNameDeleteOne) ExecX(ctx context.Context) {
	cndo.cnd.ExecX(ctx)
}
