// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/jobposition"
	"github.com/team15/app/ent/predicate"
)

// JobpositionDelete is the builder for deleting a Jobposition entity.
type JobpositionDelete struct {
	config
	hooks      []Hook
	mutation   *JobpositionMutation
	predicates []predicate.Jobposition
}

// Where adds a new predicate to the delete builder.
func (jd *JobpositionDelete) Where(ps ...predicate.Jobposition) *JobpositionDelete {
	jd.predicates = append(jd.predicates, ps...)
	return jd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (jd *JobpositionDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(jd.hooks) == 0 {
		affected, err = jd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JobpositionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			jd.mutation = mutation
			affected, err = jd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(jd.hooks) - 1; i >= 0; i-- {
			mut = jd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, jd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (jd *JobpositionDelete) ExecX(ctx context.Context) int {
	n, err := jd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (jd *JobpositionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: jobposition.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: jobposition.FieldID,
			},
		},
	}
	if ps := jd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, jd.driver, _spec)
}

// JobpositionDeleteOne is the builder for deleting a single Jobposition entity.
type JobpositionDeleteOne struct {
	jd *JobpositionDelete
}

// Exec executes the deletion query.
func (jdo *JobpositionDeleteOne) Exec(ctx context.Context) error {
	n, err := jdo.jd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{jobposition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (jdo *JobpositionDeleteOne) ExecX(ctx context.Context) {
	jdo.jd.ExecX(ctx)
}
