// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/petrule"
	"github.com/team15/app/ent/roomdetail"
)

// PetruleCreate is the builder for creating a Petrule entity.
type PetruleCreate struct {
	config
	mutation *PetruleMutation
	hooks    []Hook
}

// SetPetrule sets the petrule field.
func (pc *PetruleCreate) SetPetrule(s string) *PetruleCreate {
	pc.mutation.SetPetrule(s)
	return pc
}

// AddRoomdetailIDs adds the roomdetails edge to Roomdetail by ids.
func (pc *PetruleCreate) AddRoomdetailIDs(ids ...int) *PetruleCreate {
	pc.mutation.AddRoomdetailIDs(ids...)
	return pc
}

// AddRoomdetails adds the roomdetails edges to Roomdetail.
func (pc *PetruleCreate) AddRoomdetails(r ...*Roomdetail) *PetruleCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRoomdetailIDs(ids...)
}

// Mutation returns the PetruleMutation object of the builder.
func (pc *PetruleCreate) Mutation() *PetruleMutation {
	return pc.mutation
}

// Save creates the Petrule in the database.
func (pc *PetruleCreate) Save(ctx context.Context) (*Petrule, error) {
	if _, ok := pc.mutation.Petrule(); !ok {
		return nil, &ValidationError{Name: "petrule", err: errors.New("ent: missing required field \"petrule\"")}
	}
	var (
		err  error
		node *Petrule
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PetruleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PetruleCreate) SaveX(ctx context.Context) *Petrule {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PetruleCreate) sqlSave(ctx context.Context) (*Petrule, error) {
	pe, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pe.ID = int(id)
	return pe, nil
}

func (pc *PetruleCreate) createSpec() (*Petrule, *sqlgraph.CreateSpec) {
	var (
		pe    = &Petrule{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: petrule.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: petrule.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Petrule(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: petrule.FieldPetrule,
		})
		pe.Petrule = value
	}
	if nodes := pc.mutation.RoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   petrule.RoomdetailsTable,
			Columns: []string{petrule.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pe, _spec
}
