// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/pledge"
	"github.com/team15/app/ent/roomdetail"
)

// PledgeCreate is the builder for creating a Pledge entity.
type PledgeCreate struct {
	config
	mutation *PledgeMutation
	hooks    []Hook
}

// SetProvision sets the provision field.
func (pc *PledgeCreate) SetProvision(s string) *PledgeCreate {
	pc.mutation.SetProvision(s)
	return pc
}

// AddRoomdetailIDs adds the roomdetails edge to Roomdetail by ids.
func (pc *PledgeCreate) AddRoomdetailIDs(ids ...int) *PledgeCreate {
	pc.mutation.AddRoomdetailIDs(ids...)
	return pc
}

// AddRoomdetails adds the roomdetails edges to Roomdetail.
func (pc *PledgeCreate) AddRoomdetails(r ...*Roomdetail) *PledgeCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return pc.AddRoomdetailIDs(ids...)
}

// Mutation returns the PledgeMutation object of the builder.
func (pc *PledgeCreate) Mutation() *PledgeMutation {
	return pc.mutation
}

// Save creates the Pledge in the database.
func (pc *PledgeCreate) Save(ctx context.Context) (*Pledge, error) {
	if _, ok := pc.mutation.Provision(); !ok {
		return nil, &ValidationError{Name: "provision", err: errors.New("ent: missing required field \"provision\"")}
	}
	var (
		err  error
		node *Pledge
	)
	if len(pc.hooks) == 0 {
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PledgeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pc.mutation = mutation
			node, err = pc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PledgeCreate) SaveX(ctx context.Context) *Pledge {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pc *PledgeCreate) sqlSave(ctx context.Context) (*Pledge, error) {
	pl, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	pl.ID = int(id)
	return pl, nil
}

func (pc *PledgeCreate) createSpec() (*Pledge, *sqlgraph.CreateSpec) {
	var (
		pl    = &Pledge{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: pledge.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: pledge.FieldID,
			},
		}
	)
	if value, ok := pc.mutation.Provision(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: pledge.FieldProvision,
		})
		pl.Provision = value
	}
	if nodes := pc.mutation.RoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pledge.RoomdetailsTable,
			Columns: []string{pledge.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return pl, _spec
}
