// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/bill"
	"github.com/team15/app/ent/situation"
)

// SituationCreate is the builder for creating a Situation entity.
type SituationCreate struct {
	config
	mutation *SituationMutation
	hooks    []Hook
}

// SetSituationname sets the situationname field.
func (sc *SituationCreate) SetSituationname(s string) *SituationCreate {
	sc.mutation.SetSituationname(s)
	return sc
}

// AddSituationIDs adds the situations edge to Bill by ids.
func (sc *SituationCreate) AddSituationIDs(ids ...int) *SituationCreate {
	sc.mutation.AddSituationIDs(ids...)
	return sc
}

// AddSituations adds the situations edges to Bill.
func (sc *SituationCreate) AddSituations(b ...*Bill) *SituationCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return sc.AddSituationIDs(ids...)
}

// Mutation returns the SituationMutation object of the builder.
func (sc *SituationCreate) Mutation() *SituationMutation {
	return sc.mutation
}

// Save creates the Situation in the database.
func (sc *SituationCreate) Save(ctx context.Context) (*Situation, error) {
	if _, ok := sc.mutation.Situationname(); !ok {
		return nil, &ValidationError{Name: "situationname", err: errors.New("ent: missing required field \"situationname\"")}
	}
	if v, ok := sc.mutation.Situationname(); ok {
		if err := situation.SituationnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "situationname", err: fmt.Errorf("ent: validator failed for field \"situationname\": %w", err)}
		}
	}
	var (
		err  error
		node *Situation
	)
	if len(sc.hooks) == 0 {
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SituationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sc.mutation = mutation
			node, err = sc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			mut = sc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SituationCreate) SaveX(ctx context.Context) *Situation {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (sc *SituationCreate) sqlSave(ctx context.Context) (*Situation, error) {
	s, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	s.ID = int(id)
	return s, nil
}

func (sc *SituationCreate) createSpec() (*Situation, *sqlgraph.CreateSpec) {
	var (
		s     = &Situation{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: situation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: situation.FieldID,
			},
		}
	)
	if value, ok := sc.mutation.Situationname(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: situation.FieldSituationname,
		})
		s.Situationname = value
	}
	if nodes := sc.mutation.SituationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   situation.SituationsTable,
			Columns: []string{situation.SituationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return s, _spec
}
