// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/bill"
	"github.com/team15/app/ent/predicate"
	"github.com/team15/app/ent/situation"
)

// SituationUpdate is the builder for updating Situation entities.
type SituationUpdate struct {
	config
	hooks      []Hook
	mutation   *SituationMutation
	predicates []predicate.Situation
}

// Where adds a new predicate for the builder.
func (su *SituationUpdate) Where(ps ...predicate.Situation) *SituationUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetSituationname sets the situationname field.
func (su *SituationUpdate) SetSituationname(s string) *SituationUpdate {
	su.mutation.SetSituationname(s)
	return su
}

// AddSituationIDs adds the situations edge to Bill by ids.
func (su *SituationUpdate) AddSituationIDs(ids ...int) *SituationUpdate {
	su.mutation.AddSituationIDs(ids...)
	return su
}

// AddSituations adds the situations edges to Bill.
func (su *SituationUpdate) AddSituations(b ...*Bill) *SituationUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return su.AddSituationIDs(ids...)
}

// Mutation returns the SituationMutation object of the builder.
func (su *SituationUpdate) Mutation() *SituationMutation {
	return su.mutation
}

// RemoveSituationIDs removes the situations edge to Bill by ids.
func (su *SituationUpdate) RemoveSituationIDs(ids ...int) *SituationUpdate {
	su.mutation.RemoveSituationIDs(ids...)
	return su
}

// RemoveSituations removes situations edges to Bill.
func (su *SituationUpdate) RemoveSituations(b ...*Bill) *SituationUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return su.RemoveSituationIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *SituationUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := su.mutation.Situationname(); ok {
		if err := situation.SituationnameValidator(v); err != nil {
			return 0, &ValidationError{Name: "situationname", err: fmt.Errorf("ent: validator failed for field \"situationname\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SituationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *SituationUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SituationUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SituationUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *SituationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   situation.Table,
			Columns: situation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: situation.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Situationname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: situation.FieldSituationname,
		})
	}
	if nodes := su.mutation.RemovedSituationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   situation.SituationsTable,
			Columns: []string{situation.SituationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.SituationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   situation.SituationsTable,
			Columns: []string{situation.SituationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{situation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// SituationUpdateOne is the builder for updating a single Situation entity.
type SituationUpdateOne struct {
	config
	hooks    []Hook
	mutation *SituationMutation
}

// SetSituationname sets the situationname field.
func (suo *SituationUpdateOne) SetSituationname(s string) *SituationUpdateOne {
	suo.mutation.SetSituationname(s)
	return suo
}

// AddSituationIDs adds the situations edge to Bill by ids.
func (suo *SituationUpdateOne) AddSituationIDs(ids ...int) *SituationUpdateOne {
	suo.mutation.AddSituationIDs(ids...)
	return suo
}

// AddSituations adds the situations edges to Bill.
func (suo *SituationUpdateOne) AddSituations(b ...*Bill) *SituationUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return suo.AddSituationIDs(ids...)
}

// Mutation returns the SituationMutation object of the builder.
func (suo *SituationUpdateOne) Mutation() *SituationMutation {
	return suo.mutation
}

// RemoveSituationIDs removes the situations edge to Bill by ids.
func (suo *SituationUpdateOne) RemoveSituationIDs(ids ...int) *SituationUpdateOne {
	suo.mutation.RemoveSituationIDs(ids...)
	return suo
}

// RemoveSituations removes situations edges to Bill.
func (suo *SituationUpdateOne) RemoveSituations(b ...*Bill) *SituationUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return suo.RemoveSituationIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *SituationUpdateOne) Save(ctx context.Context) (*Situation, error) {
	if v, ok := suo.mutation.Situationname(); ok {
		if err := situation.SituationnameValidator(v); err != nil {
			return nil, &ValidationError{Name: "situationname", err: fmt.Errorf("ent: validator failed for field \"situationname\": %w", err)}
		}
	}

	var (
		err  error
		node *Situation
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SituationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SituationUpdateOne) SaveX(ctx context.Context) *Situation {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *SituationUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SituationUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *SituationUpdateOne) sqlSave(ctx context.Context) (s *Situation, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   situation.Table,
			Columns: situation.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: situation.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Situation.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Situationname(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: situation.FieldSituationname,
		})
	}
	if nodes := suo.mutation.RemovedSituationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   situation.SituationsTable,
			Columns: []string{situation.SituationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.SituationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   situation.SituationsTable,
			Columns: []string{situation.SituationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: bill.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Situation{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{situation.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
