// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/team15/app/ent/predicate"
	"github.com/team15/app/ent/roomdetail"
	"github.com/team15/app/ent/staytype"
)

// StaytypeUpdate is the builder for updating Staytype entities.
type StaytypeUpdate struct {
	config
	hooks      []Hook
	mutation   *StaytypeMutation
	predicates []predicate.Staytype
}

// Where adds a new predicate for the builder.
func (su *StaytypeUpdate) Where(ps ...predicate.Staytype) *StaytypeUpdate {
	su.predicates = append(su.predicates, ps...)
	return su
}

// SetStaytype sets the staytype field.
func (su *StaytypeUpdate) SetStaytype(s string) *StaytypeUpdate {
	su.mutation.SetStaytype(s)
	return su
}

// AddRoomdetailIDs adds the roomdetails edge to Roomdetail by ids.
func (su *StaytypeUpdate) AddRoomdetailIDs(ids ...int) *StaytypeUpdate {
	su.mutation.AddRoomdetailIDs(ids...)
	return su
}

// AddRoomdetails adds the roomdetails edges to Roomdetail.
func (su *StaytypeUpdate) AddRoomdetails(r ...*Roomdetail) *StaytypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.AddRoomdetailIDs(ids...)
}

// Mutation returns the StaytypeMutation object of the builder.
func (su *StaytypeUpdate) Mutation() *StaytypeMutation {
	return su.mutation
}

// RemoveRoomdetailIDs removes the roomdetails edge to Roomdetail by ids.
func (su *StaytypeUpdate) RemoveRoomdetailIDs(ids ...int) *StaytypeUpdate {
	su.mutation.RemoveRoomdetailIDs(ids...)
	return su
}

// RemoveRoomdetails removes roomdetails edges to Roomdetail.
func (su *StaytypeUpdate) RemoveRoomdetails(r ...*Roomdetail) *StaytypeUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return su.RemoveRoomdetailIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (su *StaytypeUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(su.hooks) == 0 {
		affected, err = su.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StaytypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			su.mutation = mutation
			affected, err = su.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(su.hooks) - 1; i >= 0; i-- {
			mut = su.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, su.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (su *StaytypeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StaytypeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StaytypeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

func (su *StaytypeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   staytype.Table,
			Columns: staytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: staytype.FieldID,
			},
		},
	}
	if ps := su.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Staytype(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staytype.FieldStaytype,
		})
	}
	if nodes := su.mutation.RemovedRoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staytype.RoomdetailsTable,
			Columns: []string{staytype.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staytype.RoomdetailsTable,
			Columns: []string{staytype.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staytype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// StaytypeUpdateOne is the builder for updating a single Staytype entity.
type StaytypeUpdateOne struct {
	config
	hooks    []Hook
	mutation *StaytypeMutation
}

// SetStaytype sets the staytype field.
func (suo *StaytypeUpdateOne) SetStaytype(s string) *StaytypeUpdateOne {
	suo.mutation.SetStaytype(s)
	return suo
}

// AddRoomdetailIDs adds the roomdetails edge to Roomdetail by ids.
func (suo *StaytypeUpdateOne) AddRoomdetailIDs(ids ...int) *StaytypeUpdateOne {
	suo.mutation.AddRoomdetailIDs(ids...)
	return suo
}

// AddRoomdetails adds the roomdetails edges to Roomdetail.
func (suo *StaytypeUpdateOne) AddRoomdetails(r ...*Roomdetail) *StaytypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.AddRoomdetailIDs(ids...)
}

// Mutation returns the StaytypeMutation object of the builder.
func (suo *StaytypeUpdateOne) Mutation() *StaytypeMutation {
	return suo.mutation
}

// RemoveRoomdetailIDs removes the roomdetails edge to Roomdetail by ids.
func (suo *StaytypeUpdateOne) RemoveRoomdetailIDs(ids ...int) *StaytypeUpdateOne {
	suo.mutation.RemoveRoomdetailIDs(ids...)
	return suo
}

// RemoveRoomdetails removes roomdetails edges to Roomdetail.
func (suo *StaytypeUpdateOne) RemoveRoomdetails(r ...*Roomdetail) *StaytypeUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return suo.RemoveRoomdetailIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (suo *StaytypeUpdateOne) Save(ctx context.Context) (*Staytype, error) {

	var (
		err  error
		node *Staytype
	)
	if len(suo.hooks) == 0 {
		node, err = suo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*StaytypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			suo.mutation = mutation
			node, err = suo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(suo.hooks) - 1; i >= 0; i-- {
			mut = suo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, suo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StaytypeUpdateOne) SaveX(ctx context.Context) *Staytype {
	s, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return s
}

// Exec executes the query on the entity.
func (suo *StaytypeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StaytypeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (suo *StaytypeUpdateOne) sqlSave(ctx context.Context) (s *Staytype, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   staytype.Table,
			Columns: staytype.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: staytype.FieldID,
			},
		},
	}
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Staytype.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := suo.mutation.Staytype(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: staytype.FieldStaytype,
		})
	}
	if nodes := suo.mutation.RemovedRoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staytype.RoomdetailsTable,
			Columns: []string{staytype.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RoomdetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   staytype.RoomdetailsTable,
			Columns: []string{staytype.RoomdetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: roomdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	s = &Staytype{config: suo.config}
	_spec.Assign = s.assignValues
	_spec.ScanValues = s.scanValues()
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{staytype.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return s, nil
}
