// Code generated by entc, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/team15/app/ent"
)

// The CleanerNameFunc type is an adapter to allow the use of ordinary
// function as CleanerName mutator.
type CleanerNameFunc func(context.Context, *ent.CleanerNameMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CleanerNameFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.CleanerNameMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CleanerNameMutation", m)
	}
	return f(ctx, mv)
}

// The CleaningRoomFunc type is an adapter to allow the use of ordinary
// function as CleaningRoom mutator.
type CleaningRoomFunc func(context.Context, *ent.CleaningRoomMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CleaningRoomFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.CleaningRoomMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CleaningRoomMutation", m)
	}
	return f(ctx, mv)
}

// The DepositFunc type is an adapter to allow the use of ordinary
// function as Deposit mutator.
type DepositFunc func(context.Context, *ent.DepositMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DepositFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.DepositMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DepositMutation", m)
	}
	return f(ctx, mv)
}

// The EmployeeFunc type is an adapter to allow the use of ordinary
// function as Employee mutator.
type EmployeeFunc func(context.Context, *ent.EmployeeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EmployeeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.EmployeeMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EmployeeMutation", m)
	}
	return f(ctx, mv)
}

// The EquipmentFunc type is an adapter to allow the use of ordinary
// function as Equipment mutator.
type EquipmentFunc func(context.Context, *ent.EquipmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EquipmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.EquipmentMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EquipmentMutation", m)
	}
	return f(ctx, mv)
}

// The FacilitieFunc type is an adapter to allow the use of ordinary
// function as Facilitie mutator.
type FacilitieFunc func(context.Context, *ent.FacilitieMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FacilitieFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.FacilitieMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FacilitieMutation", m)
	}
	return f(ctx, mv)
}

// The JobpositionFunc type is an adapter to allow the use of ordinary
// function as Jobposition mutator.
type JobpositionFunc func(context.Context, *ent.JobpositionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f JobpositionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.JobpositionMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.JobpositionMutation", m)
	}
	return f(ctx, mv)
}

// The LeaseFunc type is an adapter to allow the use of ordinary
// function as Lease mutator.
type LeaseFunc func(context.Context, *ent.LeaseMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LeaseFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.LeaseMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LeaseMutation", m)
	}
	return f(ctx, mv)
}

// The LengthTimeFunc type is an adapter to allow the use of ordinary
// function as LengthTime mutator.
type LengthTimeFunc func(context.Context, *ent.LengthTimeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LengthTimeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.LengthTimeMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LengthTimeMutation", m)
	}
	return f(ctx, mv)
}

// The NearbyplaceFunc type is an adapter to allow the use of ordinary
// function as Nearbyplace mutator.
type NearbyplaceFunc func(context.Context, *ent.NearbyplaceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f NearbyplaceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.NearbyplaceMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.NearbyplaceMutation", m)
	}
	return f(ctx, mv)
}

// The QuantityFunc type is an adapter to allow the use of ordinary
// function as Quantity mutator.
type QuantityFunc func(context.Context, *ent.QuantityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f QuantityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.QuantityMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.QuantityMutation", m)
	}
	return f(ctx, mv)
}

// The RoomdetailFunc type is an adapter to allow the use of ordinary
// function as Roomdetail mutator.
type RoomdetailFunc func(context.Context, *ent.RoomdetailMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoomdetailFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.RoomdetailMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoomdetailMutation", m)
	}
	return f(ctx, mv)
}

// The StatusdFunc type is an adapter to allow the use of ordinary
// function as Statusd mutator.
type StatusdFunc func(context.Context, *ent.StatusdMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StatusdFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.StatusdMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StatusdMutation", m)
	}
	return f(ctx, mv)
}

// The StaytypeFunc type is an adapter to allow the use of ordinary
// function as Staytype mutator.
type StaytypeFunc func(context.Context, *ent.StaytypeMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StaytypeFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.StaytypeMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StaytypeMutation", m)
	}
	return f(ctx, mv)
}

// The WifiFunc type is an adapter to allow the use of ordinary
// function as Wifi mutator.
type WifiFunc func(context.Context, *ent.WifiMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WifiFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	mv, ok := m.(*ent.WifiMutation)
	if !ok {
		return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WifiMutation", m)
	}
	return f(ctx, mv)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	Hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
//
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
//
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
//
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
//
func Reject(op ent.Op) ent.Hook {
	hk := func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(_ context.Context, m ent.Mutation) (ent.Value, error) {
			return nil, fmt.Errorf("%s operation is not allowed", m.Op())
		})
	}
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
