// Code generated by entc, DO NOT EDIT.

package lease

const (
	// Label holds the string label denoting the lease type in the database.
	Label = "lease"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAddedtime holds the string denoting the addedtime field in the database.
	FieldAddedtime = "addedtime"
	// FieldLease holds the string denoting the lease field in the database.
	FieldLease = "lease"

	// EdgeWifi holds the string denoting the wifi edge name in mutations.
	EdgeWifi = "Wifi"
	// EdgeRoomdetail holds the string denoting the roomdetail edge name in mutations.
	EdgeRoomdetail = "Roomdetail"

	// Table holds the table name of the lease in the database.
	Table = "leases"
	// WifiTable is the table the holds the Wifi relation/edge.
	WifiTable = "leases"
	// WifiInverseTable is the table name for the Wifi entity.
	// It exists in this package in order to avoid circular dependency with the "wifi" package.
	WifiInverseTable = "wifis"
	// WifiColumn is the table column denoting the Wifi relation/edge.
	WifiColumn = "wifi_id"
	// RoomdetailTable is the table the holds the Roomdetail relation/edge.
	RoomdetailTable = "leases"
	// RoomdetailInverseTable is the table name for the Roomdetail entity.
	// It exists in this package in order to avoid circular dependency with the "roomdetail" package.
	RoomdetailInverseTable = "roomdetails"
	// RoomdetailColumn is the table column denoting the Roomdetail relation/edge.
	RoomdetailColumn = "room_num"
)

// Columns holds all SQL columns for lease fields.
var Columns = []string{
	FieldID,
	FieldAddedtime,
	FieldLease,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Lease type.
var ForeignKeys = []string{
	"room_num",
	"wifi_id",
}
