// Code generated by entc, DO NOT EDIT.

package roomdetail

const (
	// Label holds the string label denoting the roomdetail type in the database.
	Label = "roomdetail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldRoomnumber holds the string denoting the roomnumber field in the database.
	FieldRoomnumber = "roomnumber"
	// FieldRoomtypename holds the string denoting the roomtypename field in the database.
	FieldRoomtypename = "roomtypename"
	// FieldRoomprice holds the string denoting the roomprice field in the database.
	FieldRoomprice = "roomprice"

	// EdgeEquipments holds the string denoting the equipments edge name in mutations.
	EdgeEquipments = "equipments"
	// EdgeFacilities holds the string denoting the facilities edge name in mutations.
	EdgeFacilities = "facilities"
	// EdgeNearbyplaces holds the string denoting the nearbyplaces edge name in mutations.
	EdgeNearbyplaces = "nearbyplaces"
	// EdgeEmployee holds the string denoting the employee edge name in mutations.
	EdgeEmployee = "employee"
	// EdgeQuantity holds the string denoting the quantity edge name in mutations.
	EdgeQuantity = "quantity"
	// EdgeStaytype holds the string denoting the staytype edge name in mutations.
	EdgeStaytype = "staytype"
	// EdgeRoomdetails holds the string denoting the roomdetails edge name in mutations.
	EdgeRoomdetails = "roomdetails"

	// Table holds the table name of the roomdetail in the database.
	Table = "roomdetails"
	// EquipmentsTable is the table the holds the equipments relation/edge.
	EquipmentsTable = "roomdetails"
	// EquipmentsInverseTable is the table name for the Equipment entity.
	// It exists in this package in order to avoid circular dependency with the "equipment" package.
	EquipmentsInverseTable = "equipment"
	// EquipmentsColumn is the table column denoting the equipments relation/edge.
	EquipmentsColumn = "equipment_roomdetail"
	// FacilitiesTable is the table the holds the facilities relation/edge.
	FacilitiesTable = "roomdetails"
	// FacilitiesInverseTable is the table name for the Facilitie entity.
	// It exists in this package in order to avoid circular dependency with the "facilitie" package.
	FacilitiesInverseTable = "facilities"
	// FacilitiesColumn is the table column denoting the facilities relation/edge.
	FacilitiesColumn = "facilitie_roomdetail"
	// NearbyplacesTable is the table the holds the nearbyplaces relation/edge.
	NearbyplacesTable = "roomdetails"
	// NearbyplacesInverseTable is the table name for the Nearbyplace entity.
	// It exists in this package in order to avoid circular dependency with the "nearbyplace" package.
	NearbyplacesInverseTable = "nearbyplaces"
	// NearbyplacesColumn is the table column denoting the nearbyplaces relation/edge.
	NearbyplacesColumn = "nearbyplace_roomdetail"
	// EmployeeTable is the table the holds the employee relation/edge.
	EmployeeTable = "roomdetails"
	// EmployeeInverseTable is the table name for the Employee entity.
	// It exists in this package in order to avoid circular dependency with the "employee" package.
	EmployeeInverseTable = "employees"
	// EmployeeColumn is the table column denoting the employee relation/edge.
	EmployeeColumn = "employee_id"
	// QuantityTable is the table the holds the quantity relation/edge.
	QuantityTable = "roomdetails"
	// QuantityInverseTable is the table name for the Quantity entity.
	// It exists in this package in order to avoid circular dependency with the "quantity" package.
	QuantityInverseTable = "quantities"
	// QuantityColumn is the table column denoting the quantity relation/edge.
	QuantityColumn = "quantity_roomdetails"
	// StaytypeTable is the table the holds the staytype relation/edge.
	StaytypeTable = "roomdetails"
	// StaytypeInverseTable is the table name for the Staytype entity.
	// It exists in this package in order to avoid circular dependency with the "staytype" package.
	StaytypeInverseTable = "staytypes"
	// StaytypeColumn is the table column denoting the staytype relation/edge.
	StaytypeColumn = "staytype_roomdetails"
	// RoomdetailsTable is the table the holds the roomdetails relation/edge.
	RoomdetailsTable = "leases"
	// RoomdetailsInverseTable is the table name for the Lease entity.
	// It exists in this package in order to avoid circular dependency with the "lease" package.
	RoomdetailsInverseTable = "leases"
	// RoomdetailsColumn is the table column denoting the roomdetails relation/edge.
	RoomdetailsColumn = "room_num"
)

// Columns holds all SQL columns for roomdetail fields.
var Columns = []string{
	FieldID,
	FieldRoomnumber,
	FieldRoomtypename,
	FieldRoomprice,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Roomdetail type.
var ForeignKeys = []string{
	"employee_id",
	"equipment_roomdetail",
	"facilitie_roomdetail",
	"nearbyplace_roomdetail",
	"quantity_roomdetails",
	"staytype_roomdetails",
}

var (
	// RoomnumberValidator is a validator for the "roomnumber" field. It is called by the builders before save.
	RoomnumberValidator func(string) error
	// RoomtypenameValidator is a validator for the "roomtypename" field. It is called by the builders before save.
	RoomtypenameValidator func(string) error
	// RoompriceValidator is a validator for the "roomprice" field. It is called by the builders before save.
	RoompriceValidator func(string) error
)
