/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomdetail,
    EntRoomdetailFromJSON,
    EntRoomdetailFromJSONTyped,
    EntRoomdetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEquipmentEdges
 */
export interface EntEquipmentEdges {
    /**
     * Roomdetail holds the value of the roomdetail edge.
     * @type {Array<EntRoomdetail>}
     * @memberof EntEquipmentEdges
     */
    roomdetail?: Array<EntRoomdetail>;
}

export function EntEquipmentEdgesFromJSON(json: any): EntEquipmentEdges {
    return EntEquipmentEdgesFromJSONTyped(json, false);
}

export function EntEquipmentEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEquipmentEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomdetail': !exists(json, 'Roomdetail') ? undefined : ((json['Roomdetail'] as Array<any>).map(EntRoomdetailFromJSON)),
    };
}

export function EntEquipmentEdgesToJSON(value?: EntEquipmentEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomdetail': value.roomdetail === undefined ? undefined : ((value.roomdetail as Array<any>).map(EntRoomdetailToJSON)),
    };
}


