/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomdetail,
    EntRoomdetailFromJSON,
    EntRoomdetailFromJSONTyped,
    EntRoomdetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntFacilitieEdges
 */
export interface EntFacilitieEdges {
    /**
     * 
     * @type {EntRoomdetail}
     * @memberof EntFacilitieEdges
     */
    roomdetail?: EntRoomdetail;
}

export function EntFacilitieEdgesFromJSON(json: any): EntFacilitieEdges {
    return EntFacilitieEdgesFromJSONTyped(json, false);
}

export function EntFacilitieEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntFacilitieEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roomdetail': !exists(json, 'roomdetail') ? undefined : EntRoomdetailFromJSON(json['roomdetail']),
    };
}

export function EntFacilitieEdgesToJSON(value?: EntFacilitieEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roomdetail': EntRoomdetailToJSON(value.roomdetail),
    };
}


