/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEquipment,
    EntEquipmentFromJSON,
    EntEquipmentFromJSONTyped,
    EntEquipmentToJSON,
    EntFacility,
    EntFacilityFromJSON,
    EntFacilityFromJSONTyped,
    EntFacilityToJSON,
    EntNearbyPlace,
    EntNearbyPlaceFromJSON,
    EntNearbyPlaceFromJSONTyped,
    EntNearbyPlaceToJSON,
    EntQuantity,
    EntQuantityFromJSON,
    EntQuantityFromJSONTyped,
    EntQuantityToJSON,
    EntStayType,
    EntStayTypeFromJSON,
    EntStayTypeFromJSONTyped,
    EntStayTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomEdges
 */
export interface EntRoomEdges {
    /**
     * Equipments holds the value of the equipments edge.
     * @type {Array<EntEquipment>}
     * @memberof EntRoomEdges
     */
    equipments?: Array<EntEquipment>;
    /**
     * Facilities holds the value of the facilities edge.
     * @type {Array<EntFacility>}
     * @memberof EntRoomEdges
     */
    facilities?: Array<EntFacility>;
    /**
     * Nearbyplace holds the value of the nearbyplace edge.
     * @type {Array<EntNearbyPlace>}
     * @memberof EntRoomEdges
     */
    nearbyplace?: Array<EntNearbyPlace>;
    /**
     * 
     * @type {EntQuantity}
     * @memberof EntRoomEdges
     */
    quantity?: EntQuantity;
    /**
     * 
     * @type {EntStayType}
     * @memberof EntRoomEdges
     */
    staytype?: EntStayType;
}

export function EntRoomEdgesFromJSON(json: any): EntRoomEdges {
    return EntRoomEdgesFromJSONTyped(json, false);
}

export function EntRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'equipments': !exists(json, 'equipments') ? undefined : ((json['equipments'] as Array<any>).map(EntEquipmentFromJSON)),
        'facilities': !exists(json, 'facilities') ? undefined : ((json['facilities'] as Array<any>).map(EntFacilityFromJSON)),
        'nearbyplace': !exists(json, 'nearbyplace') ? undefined : ((json['nearbyplace'] as Array<any>).map(EntNearbyPlaceFromJSON)),
        'quantity': !exists(json, 'quantity') ? undefined : EntQuantityFromJSON(json['quantity']),
        'staytype': !exists(json, 'staytype') ? undefined : EntStayTypeFromJSON(json['staytype']),
    };
}

export function EntRoomEdgesToJSON(value?: EntRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'equipments': value.equipments === undefined ? undefined : ((value.equipments as Array<any>).map(EntEquipmentToJSON)),
        'facilities': value.facilities === undefined ? undefined : ((value.facilities as Array<any>).map(EntFacilityToJSON)),
        'nearbyplace': value.nearbyplace === undefined ? undefined : ((value.nearbyplace as Array<any>).map(EntNearbyPlaceToJSON)),
        'quantity': EntQuantityToJSON(value.quantity),
        'staytype': EntStayTypeToJSON(value.staytype),
    };
}


