// Code generated by entc, DO NOT EDIT.

package statusd

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/team15/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Statusdname applies equality check predicate on the "statusdname" field. It's identical to StatusdnameEQ.
func Statusdname(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusdname), v))
	})
}

// StatusdnameEQ applies the EQ predicate on the "statusdname" field.
func StatusdnameEQ(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatusdname), v))
	})
}

// StatusdnameNEQ applies the NEQ predicate on the "statusdname" field.
func StatusdnameNEQ(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatusdname), v))
	})
}

// StatusdnameIn applies the In predicate on the "statusdname" field.
func StatusdnameIn(vs ...string) predicate.Statusd {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statusd(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatusdname), v...))
	})
}

// StatusdnameNotIn applies the NotIn predicate on the "statusdname" field.
func StatusdnameNotIn(vs ...string) predicate.Statusd {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Statusd(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatusdname), v...))
	})
}

// StatusdnameGT applies the GT predicate on the "statusdname" field.
func StatusdnameGT(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldStatusdname), v))
	})
}

// StatusdnameGTE applies the GTE predicate on the "statusdname" field.
func StatusdnameGTE(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldStatusdname), v))
	})
}

// StatusdnameLT applies the LT predicate on the "statusdname" field.
func StatusdnameLT(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldStatusdname), v))
	})
}

// StatusdnameLTE applies the LTE predicate on the "statusdname" field.
func StatusdnameLTE(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldStatusdname), v))
	})
}

// StatusdnameContains applies the Contains predicate on the "statusdname" field.
func StatusdnameContains(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldStatusdname), v))
	})
}

// StatusdnameHasPrefix applies the HasPrefix predicate on the "statusdname" field.
func StatusdnameHasPrefix(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldStatusdname), v))
	})
}

// StatusdnameHasSuffix applies the HasSuffix predicate on the "statusdname" field.
func StatusdnameHasSuffix(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldStatusdname), v))
	})
}

// StatusdnameEqualFold applies the EqualFold predicate on the "statusdname" field.
func StatusdnameEqualFold(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldStatusdname), v))
	})
}

// StatusdnameContainsFold applies the ContainsFold predicate on the "statusdname" field.
func StatusdnameContainsFold(v string) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldStatusdname), v))
	})
}

// HasStatusds applies the HasEdge predicate on the "statusds" edge.
func HasStatusds() predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatusdsTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatusdsTable, StatusdsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStatusdsWith applies the HasEdge predicate on the "statusds" edge with a given conditions (other predicates).
func HasStatusdsWith(preds ...predicate.Deposit) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(StatusdsInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, StatusdsTable, StatusdsColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Statusd) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Statusd) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Statusd) predicate.Statusd {
	return predicate.Statusd(func(s *sql.Selector) {
		p(s.Not())
	})
}
